[features]
seeds = false
skip-lint = false
[programs.localnet]
pendulum = "Ercwg63fCFawCuVrExYFFumXxyt4DVAHVpmjLPLCA2yB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
